### ISSUE TITLE
Question Type

### ISSUE THREAD

**Issue by SRL94** [czy1999/SubGTR#3]
Does the question contain multi-hop questions? For example, "who was the first President of the USA after world war II?", the important question entity is "the President of the USA" (Q11696). In this question, answers are direct neighbours (or 1hop neighbours) of "the President of the USA". Does your dataset contain multi-hop questions from the important question entity? Many thanks.

**Comment by czy1999** [comment]
Yes, all questions in CronQuestions are within 1-hop. Our Complex-CronQuestions dataset was obtained by filtering on CronQuestions, again without multi-hop answers.
